spring:
  application:
    name: sns-post-service
  datasource:
    url: jdbc:mysql://localhost:13306/postdb
    username: root
    password: rootpassword

  flyway:
    enabled: true
    locations: classpath:db/migration
    placeholders:
      ignore: --

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        highlight_sql: true

server:
  port: 8081

springdoc:
  swagger-ui:
    enabled: true

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.type.descriptor.sql: TRACE
