ALTER TABLE posts
ADD COLUMN delete_yn TINYINT(1) NOT NULL DEFAULT 0;

ALTER TABLE post_images
ADD COLUMN delete_yn TINYINT(1) NOT NULL DEFAULT 0,
ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE comments
ADD COLUMN delete_yn TINYINT(1) NOT NULL DEFAULT 0;